server:
  # 포트 번호를 랜덤하게 설정
  port: 0

spring:
  application:
    name: user-service

eureka:
  instance:
#    spring.cloud.client.hostname : IP 주소
#    ${spring.application.instance_id:${random.value}} : 고유값
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
#    이 서비스를 유레카 서버(디스커버리 서비스)에 등록할 것이다
    register-with-eureka: true
#    유레카 서버로부터 인스턴스들의 정보를 주기적으로 가져온다
    fetch-registry: true
#    유레카 서버의 위치
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka