server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: file://C:\workspace\spring-boot\spring-cloud-msa\e-commerce\git-local-repo
#          uri: https://github.com/~  github uri ??
#          private ??????? username, password ?? ??
#          username:
#          password:

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh